### ISSUE TITLE
Release on puppet forge

### ISSUE THREAD

**Issue by johanek** [wyrie/puppet-snmptt#1]
Do you think you could release this module on the puppet forge? We use this, and there's no other snmptt module on there. It makes our CI runs much faster to pull dependencies from the forge rather than github.

Thanks!

**Comment by wyrie** [comment]
Added it. Made a small change to the grant syntax for the database - in case you use that you may want to check compatibility.

**Comment by johanek** [comment]
Thanks so much for doing this! I don't use the DB stuff so should be good.

I realised we had a few other config changes in our setup - I need to create a PR to integrate them when I have time.

Thanks again
